# Generated by Django 4.1.4 on 2023-01-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20),
        ),
    ]
